### ISSUE TITLE
Fix a run.sh and a setup.sh

### ISSUE THREAD

**Issue by Acksell** [HelmerNylen/kons-screen#19]
Installation, setup and the process of running the scripts proved to be a tedious process, we should simplify this.

**Comment by gyback** [comment]
Are we unable to install `node`/`nodejs` if it isn't already installed?

Can't we simply check to see if there is a `/frontend/node_modules` and remove it before `npm install`?

**Comment by gyback** [comment]
Vi kan väl installera nodejs genom:
`curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs`

Hittade det på :[https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions](url)
@Acksell

**Comment by Acksell** [comment]
Jo, jag övervägde detta men beslutade att överlåta det till användaren att bestämma hur den ska konfigurera sin nodejs- och python-miljö. Men du har rätt att vi kan installera det i fallet då användaren helt saknar någon node-installation.

Angående borttagningen av `node_modules` så kan vi prompta användaren om det. Jag ville inte göra det automatiskt då användaren kanske hade en fungerande modul som den ville behålla.

**Comment by gyback** [comment]
Låter vettigt.
Man kan alltid lägga det under en y/n så att användaren får ett val. Då med en ordentlig förklaring innan.
